# Generated by Django 4.0.5 on 2022-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
